# fly.toml app configuration file generated for copypaste-fyi-withered-darkness-575 on 2025-11-02T21:10:19-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'copypaste-fyi-withered-darkness-575'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile.backend'

[env]
  ROCKET_ADDRESS = '0.0.0.0'
  ROCKET_PORT = '8000'
  RUST_LOG = 'info'
  CRYPTO_VERIFIER_URL = 'http://localhost:8001'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service]]
  internal_port = 8001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['crypto-verifier']

[processes]
  app = 'copypaste'
  crypto-verifier = 'crypto-verifier'

[[vm]]
  size = 'shared-cpu-1x'
